name: "debianize"
branding:
  color: red
  icon: package
description: >
  Genrate and build a Debian package.
inputs:
  identity:
    description: >
      Identity to use for commits
    required: false
    default: 'debianize <noreply@github.com>'
  directory:
    description: >
      Set debianize --directory option.

      Directory to run in
    required: false
  recursive:
    description: >
      Recursively package dependencies.
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.identity }}
    - ${{ inputs.directory }}
    - ${{ inputs.recursive }}
